### ISSUE TITLE
Documentation for MCPTAM is all over the place

### ISSUE THREAD

**Issue by stevenwaslander** [wavelab/mcptam#3]
We need to aggregate architecture design and software design documents into the Github wiki, and we need to add in all of the issues listed there and start the prioritization tasks.

**Comment by stevenwaslander** [comment]
We need to decide what goes in the wiki and what goes in doxygen, and how to keep them aligned.  Should we keep figures of the block diagram in Lucidcharts, is there a plugin for Lucidcharts on Github, can the wiki be synced with Doxygen documentation?

**Comment by chutsu** [comment]
In my opinion, having a wiki introduces mismatches between that and code. I reckon putting the documentation with the code (e.g. docs folder) makes more sense. Additionally one can setup docs to be hosted by github (they call it github pages) by creating a gh-pages branch (https://pages.github.com/). Note: you are not forced to use github's website generator, it serves websites statically, so at the bare minimal level you need to have an "index.html" file in the gh-pages branch.

As for tools to create software architecture, UMLGraph (http://www.umlgraph.org/doc/ceg-adv.html) seems to be a good solution, I have not personally used it but the ability to generate the diagrams via text would save a lot of mouse and click time.

**Comment by stevenwaslander** [comment]
OK, I now see what you are talking about.  Yes, I like the idea of pages.  The wiki is this weird separate thing, but the pages are in the same repo, and so are automatically cloned, seen more readily, etc.  

It also looks like we can link doxygen in, but that is less smooth than hoped for.

**Comment by stevenwaslander** [comment]
OK, upon review, I don't think gh-pages is the way to go.  We are either required to edit raw html, or use something like Jekyll that generates the pages from markdown, and requires experience developing site templates in Ruby.  Instead we'll stick to the following plan
1. Main readme for license, description and links
2. Wiki for install, software architecture, high-level planning.
3. Issues and milestones for low-level planning.
4. Doxygen for code comments, parameter settings and API definition.

**Comment by stevenwaslander** [comment]
Getting started documentation updated with script and bag file run instructions. Closing issue unilaterally.
