### ISSUE TITLE
Clean up mcptam code using roslint and astyle

### ISSUE THREAD

**Issue by stevenwaslander** [wavelab/mcptam#33]

**Comment by stevenwaslander** [comment]
Steps being used:
1. Use Astyle on .h and .cc files to clean up whitespace issues.
   
   ```
     find -regextype egrep -regex '.*\.[ch](c)?$' -exec astyle '{}' --style=allman --indent=spaces=2 --pad-oper --unpad-paren --pad-header --convert-tabs \;
   ```
2. Use clang to clean up comments and lines that run over.
   
   ```
     find . -name '*.cc' | xargs clang-format-3.6 --i -style=file $1
   ```
3. Run roslint on package by following instructions for catkin_make: http://wiki.ros.org/roslint . Note that the .cc files do not automatically get checked, as roslint only looks for .cpp extensions. To remedy this, do TBD.
4. Fix all remaining issues manually.

**Comment by StanJBrown** [comment]
For 3 should we look at just renaming all the .cc files to .cpp? I can do
it with a script.

Cheers,
Stan

On Wed, Jan 20, 2016 at 12:13 PM, Steven Waslander <notifications@github.com

**Comment by stevenwaslander** [comment]
Thanks Stan, I've done that already locally, but was looking at how to change what roslint looks at instead, as there does not seem to be a strong preference for cc or cpp out there.

Update: cpp is the standard for ROS packages.  So we'll switch in a separate issue.

**Comment by stevenwaslander** [comment]
Completed, but didn't auto close.
