### ISSUE TITLE
mcptam_install script bug

### ISSUE THREAD

**Issue by arunxdas** [wavelab/mcptam#41]
right now assumes that you are building the catkin workspace for the first time, so if you already have a catkin workspace initialized, it will complain: File catkin_ws/src/CMakeLists.txt" already exists. Should add a check in the scrip to see if the catkin workspace has already been initialized.

**Comment by stevenwaslander** [comment]
Also, puts the workspace at /home/user/ and so won't allow for any other location for install of mcptam.  The workspace part should be in the ros_install script, and then the mcptam script should be written to run from where it is.

**Comment by StanJBrown** [comment]
What do you guys think about adding a symlink rather than copying it over?

Cheers,
Stan

**Comment by stevenwaslander** [comment]
What do you mean?

**Comment by stevenwaslander** [comment]
There was also an order bug in build_dependencies that didn't clean up build_deps. Have started on this issue.

**Comment by stevenwaslander** [comment]
Ah shoot, and the CI method for grabbing mcptam doesn't work outside of TravisCI.

**Comment by StanJBrown** [comment]
What I meant by my earlier comment is if someone downloads the code into a
folder and has a catkin_ws already working I can add a symlink between the
mcptam base folder and the catkin_ws instead of copying it over.
Alternatively we could also just instruct people who have a catkin_ws
already built to just download mcptam directly into it and then run the
dependencies script followed catkin_make

**Comment by stevenwaslander** [comment]
Ah, that's nice, could work for CI version too, which copies the whole mess over from the directory the script was launched from.

**Comment by rebellojason7** [comment]
1) Change line 106 form 'cd ..' to either 'cd ' or 'cd ~'. The 'cd ..' takes us out of home repo and hence cant copy mcptam to catkin workspace
2) Add: echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc

**Comment by stevenwaslander** [comment]
So we needed different methods for user install and mcptam install, but with huge overlap.

**Comment by stevenwaslander** [comment]
pull request #43 should solve the issues with the install script for users.
