### ISSUE TITLE
Functionalize EvaluatePoint in EntropyComputation.cpp 

### ISSUE THREAD

**Issue by SabaAflaki** [wavelab/mcptam#49]

**Comment by SabaAflaki** [comment]
Could you please take a look. I left Arun's original code in comments in case you want to revert. I thought of adding a ConvertToMotionInImage function as well, I'm not sure if it will be used in other places and what the best input/outputs would be. We can discuss this later.

**Comment by arunxdas** [comment]
confirm output of functionalized version is consistent with original version
