### ISSUE TITLE
Set up Travis CI for MCPTAM

### ISSUE THREAD

**Issue by stevenwaslander** [wavelab/mcptam#6]
We need to create a travis.yml file to do all the dependency installations first, then try to compile MCPTAM and run it on a standard bag.

**Comment by stevenwaslander** [comment]
No other tests are needed.  Ubuntu 14.04 and ROS-Indigo only.

**Comment by chutsu** [comment]
@wavelab/mcptam-team Got travis up and running, please review #8

**Comment by stevenwaslander** [comment]
Nice work, left a couple small questions/comments. That was non trivial, thanks! :shipit:

**Comment by stevenwaslander** [comment]
Now really :+1:

**Comment by stevenwaslander** [comment]
Turns out there were some issues with installing everything as sudo, instead of only doing the necessary parts.  @arunxdas has the fixes locally, we should make a branch and sort out the fixes.
